package entities;
// Generated Aug 11, 2016 10:25:57 AM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "Customers", catalog = "vzsoft_chicken_team")
public class Customers implements java.io.Serializable {

	private int customerId;
	private String customerName;
	private String address;
	private String phoneNumber;
	private String email;
	private String accountNumber;
	private String identityCardNo;
	private String notes;
	private BigDecimal salary;
	private String createLog;
	private boolean isArchive;
	private Set<Contracts> contractses = new HashSet<Contracts>(0);

	public Customers() {
	}

	public Customers(int customerId, String customerName, String address, String phoneNumber, String email,
			String accountNumber, String identityCardNo, String notes, String createLog, boolean isArchive) {
		this.customerId = customerId;
		this.customerName = customerName;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.accountNumber = accountNumber;
		this.identityCardNo = identityCardNo;
		this.notes = notes;
		this.createLog = createLog;
		this.isArchive = isArchive;
	}

	public Customers(int customerId, String customerName, String address, String phoneNumber, String email,
			String accountNumber, String identityCardNo, String notes, BigDecimal salary, String createLog,
			boolean isArchive, Set<Contracts> contractses) {
		this.customerId = customerId;
		this.customerName = customerName;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.accountNumber = accountNumber;
		this.identityCardNo = identityCardNo;
		this.notes = notes;
		this.salary = salary;
		this.createLog = createLog;
		this.isArchive = isArchive;
		this.contractses = contractses;
	}

	@Id

	@Column(name = "customerId", unique = true, nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "customerName", nullable = false, length = 100)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "address", nullable = false, length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phoneNumber", nullable = false, length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "accountNumber", nullable = false, length = 20)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "identityCardNo", nullable = false, length = 20)
	public String getIdentityCardNo() {
		return this.identityCardNo;
	}

	public void setIdentityCardNo(String identityCardNo) {
		this.identityCardNo = identityCardNo;
	}

	@Column(name = "notes", nullable = false, length = 1073741823)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "salary", scale = 4)
	public BigDecimal getSalary() {
		return this.salary;
	}

	public void setSalary(BigDecimal salary) {
		this.salary = salary;
	}

	@Column(name = "createLog", nullable = false, length = 30)
	public String getCreateLog() {
		return this.createLog;
	}

	public void setCreateLog(String createLog) {
		this.createLog = createLog;
	}

	@Column(name = "isArchive", nullable = false)
	public boolean isIsArchive() {
		return this.isArchive;
	}

	public void setIsArchive(boolean isArchive) {
		this.isArchive = isArchive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customers")
	public Set<Contracts> getContractses() {
		return this.contractses;
	}

	public void setContractses(Set<Contracts> contractses) {
		this.contractses = contractses;
	}

}
