package entities;
// Generated Aug 7, 2016 11:38:34 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "Department", catalog = "vzsoft_chicken_team")
public class Department implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int departmentId;
	private LoanTypes loanTypes;
	private String departmentName;
	private Set<Staffs> staffses = new HashSet<Staffs>(0);

	public Department() {
	}

	public Department(int departmentId, LoanTypes loanTypes, String departmentName) {
		this.departmentId = departmentId;
		this.loanTypes = loanTypes;
		this.departmentName = departmentName;
	}

	public Department(int departmentId, LoanTypes loanTypes, String departmentName, Set<Staffs> staffses) {
		this.departmentId = departmentId;
		this.loanTypes = loanTypes;
		this.departmentName = departmentName;
		this.staffses = staffses;
	}

	@Id

	@Column(name = "departmentID", unique = true, nullable = false)
	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loanTypeID", nullable = false)
	public LoanTypes getLoanTypes() {
		return this.loanTypes;
	}

	public void setLoanTypes(LoanTypes loanTypes) {
		this.loanTypes = loanTypes;
	}

	@Column(name = "departmentName", nullable = false, length = 50)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Staffs> getStaffses() {
		return this.staffses;
	}

	public void setStaffses(Set<Staffs> staffses) {
		this.staffses = staffses;
	}

}
