package entities;
// Generated Aug 11, 2016 1:42:11 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "Department", catalog = "vzsoft_chicken_team")
public class Department implements java.io.Serializable {

	private int departmentId;
	private LoanTypes loanTypes;
	private String departmentName;
	private String createLog;
	private boolean isArchive;
	private Set<Staffs> staffses = new HashSet<Staffs>(0);

	public Department() {
	}

	public Department(int departmentId, LoanTypes loanTypes, String departmentName, String createLog,
			boolean isArchive) {
		this.departmentId = departmentId;
		this.loanTypes = loanTypes;
		this.departmentName = departmentName;
		this.createLog = createLog;
		this.isArchive = isArchive;
	}

	public Department(int departmentId, LoanTypes loanTypes, String departmentName, String createLog, boolean isArchive,
			Set<Staffs> staffses) {
		this.departmentId = departmentId;
		this.loanTypes = loanTypes;
		this.departmentName = departmentName;
		this.createLog = createLog;
		this.isArchive = isArchive;
		this.staffses = staffses;
	}

	@Id

	@Column(name = "departmentID", unique = true, nullable = false)
	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loanTypeID", nullable = false)
	public LoanTypes getLoanTypes() {
		return this.loanTypes;
	}

	public void setLoanTypes(LoanTypes loanTypes) {
		this.loanTypes = loanTypes;
	}

	@Column(name = "departmentName", nullable = false, length = 50)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@Column(name = "createLog", nullable = false, length = 30)
	public String getCreateLog() {
		return this.createLog;
	}

	public void setCreateLog(String createLog) {
		this.createLog = createLog;
	}

	@Column(name = "isArchive", nullable = false)
	public boolean isIsArchive() {
		return this.isArchive;
	}

	public void setIsArchive(boolean isArchive) {
		this.isArchive = isArchive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Staffs> getStaffses() {
		return this.staffses;
	}

	public void setStaffses(Set<Staffs> staffses) {
		this.staffses = staffses;
	}

}
