package entities;
// Generated Aug 11, 2016 10:25:57 AM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoanTypes generated by hbm2java
 */
@Entity
@Table(name = "LoanTypes", catalog = "vzsoft_chicken_team")
public class LoanTypes implements java.io.Serializable {

	private int loanTypeId;
	private String loanTypeName;
	private BigDecimal interestRate;
	private BigDecimal loanBase;
	private long loanRate;
	private String createLog;
	private boolean isArchive;
	private Set<Contracts> contractses = new HashSet<Contracts>(0);
	private Set<Department> departments = new HashSet<Department>(0);

	public LoanTypes() {
	}

	public LoanTypes(int loanTypeId, String loanTypeName, BigDecimal interestRate, BigDecimal loanBase, long loanRate,
			String createLog, boolean isArchive) {
		this.loanTypeId = loanTypeId;
		this.loanTypeName = loanTypeName;
		this.interestRate = interestRate;
		this.loanBase = loanBase;
		this.loanRate = loanRate;
		this.createLog = createLog;
		this.isArchive = isArchive;
	}

	public LoanTypes(int loanTypeId, String loanTypeName, BigDecimal interestRate, BigDecimal loanBase, long loanRate,
			String createLog, boolean isArchive, Set<Contracts> contractses, Set<Department> departments) {
		this.loanTypeId = loanTypeId;
		this.loanTypeName = loanTypeName;
		this.interestRate = interestRate;
		this.loanBase = loanBase;
		this.loanRate = loanRate;
		this.createLog = createLog;
		this.isArchive = isArchive;
		this.contractses = contractses;
		this.departments = departments;
	}

	@Id

	@Column(name = "loanTypeId", unique = true, nullable = false)
	public int getLoanTypeId() {
		return this.loanTypeId;
	}

	public void setLoanTypeId(int loanTypeId) {
		this.loanTypeId = loanTypeId;
	}

	@Column(name = "loanTypeName", nullable = false, length = 100)
	public String getLoanTypeName() {
		return this.loanTypeName;
	}

	public void setLoanTypeName(String loanTypeName) {
		this.loanTypeName = loanTypeName;
	}

	@Column(name = "interestRate", nullable = false, scale = 4)
	public BigDecimal getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(BigDecimal interestRate) {
		this.interestRate = interestRate;
	}

	@Column(name = "loanBase", nullable = false, scale = 4)
	public BigDecimal getLoanBase() {
		return this.loanBase;
	}

	public void setLoanBase(BigDecimal loanBase) {
		this.loanBase = loanBase;
	}

	@Column(name = "loanRate", nullable = false, precision = 18, scale = 0)
	public long getLoanRate() {
		return this.loanRate;
	}

	public void setLoanRate(long loanRate) {
		this.loanRate = loanRate;
	}

	@Column(name = "createLog", nullable = false, length = 30)
	public String getCreateLog() {
		return this.createLog;
	}

	public void setCreateLog(String createLog) {
		this.createLog = createLog;
	}

	@Column(name = "isArchive", nullable = false)
	public boolean isIsArchive() {
		return this.isArchive;
	}

	public void setIsArchive(boolean isArchive) {
		this.isArchive = isArchive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loanTypes")
	public Set<Contracts> getContractses() {
		return this.contractses;
	}

	public void setContractses(Set<Contracts> contractses) {
		this.contractses = contractses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loanTypes")
	public Set<Department> getDepartments() {
		return this.departments;
	}

	public void setDepartments(Set<Department> departments) {
		this.departments = departments;
	}

}
