package entities;
// Generated Aug 7, 2016 11:38:34 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoanTypes generated by hbm2java
 */
@Entity
@Table(name = "LoanTypes", catalog = "vzsoft_chicken_team")
public class LoanTypes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int loanTypeId;
	private String loanTypeName;
	private BigDecimal interestRate;
	private BigDecimal loanBase;
	private long loanRate;
	private Set<Department> departments = new HashSet<Department>(0);

	public LoanTypes() {
	}

	public LoanTypes(int loanTypeId, String loanTypeName, BigDecimal interestRate, BigDecimal loanBase, long loanRate) {
		this.loanTypeId = loanTypeId;
		this.loanTypeName = loanTypeName;
		this.interestRate = interestRate;
		this.loanBase = loanBase;
		this.loanRate = loanRate;
	}

	public LoanTypes(int loanTypeId, String loanTypeName, BigDecimal interestRate, BigDecimal loanBase, long loanRate,
			Set<Department> departments) {
		this.loanTypeId = loanTypeId;
		this.loanTypeName = loanTypeName;
		this.interestRate = interestRate;
		this.loanBase = loanBase;
		this.loanRate = loanRate;
		this.departments = departments;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "loanTypeId", unique = true, nullable = false)
	public int getLoanTypeId() {
		return this.loanTypeId;
	}

	public void setLoanTypeId(int loanTypeId) {
		this.loanTypeId = loanTypeId;
	}

	@Column(name = "loanTypeName", nullable = false, length = 100)
	public String getLoanTypeName() {
		return this.loanTypeName;
	}

	public void setLoanTypeName(String loanTypeName) {
		this.loanTypeName = loanTypeName;
	}

	@Column(name = "interestRate", nullable = false, scale = 4)
	public BigDecimal getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(BigDecimal interestRate) {
		this.interestRate = interestRate;
	}

	@Column(name = "loanBase", nullable = false, scale = 4)
	public BigDecimal getLoanBase() {
		return this.loanBase;
	}

	public void setLoanBase(BigDecimal loanBase) {
		this.loanBase = loanBase;
	}

	@Column(name = "loanRate", nullable = false, precision = 18, scale = 0)
	public long getLoanRate() {
		return this.loanRate;
	}

	public void setLoanRate(long loanRate) {
		this.loanRate = loanRate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loanTypes")
	public Set<Department> getDepartments() {
		return this.departments;
	}

	public void setDepartments(Set<Department> departments) {
		this.departments = departments;
	}

}
