package entities;
// Generated Aug 7, 2016 11:38:34 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "Payment", catalog = "vzsoft_chicken_team")
public class Payment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int paymentId;
	private Staffs staffs;
	private int contractId;
	private int paymentType;
	private String paymentDate;
	private int duePeriod;
	private BigDecimal paymentAmount;
	private long fineRate;
	private BigDecimal fineAmount;
	private boolean paid;

	public Payment() {
	}

	public Payment(int paymentId, Staffs staffs, int contractId, int paymentType, String paymentDate, int duePeriod,
			BigDecimal paymentAmount, long fineRate, BigDecimal fineAmount, boolean paid) {
		this.paymentId = paymentId;
		this.staffs = staffs;
		this.contractId = contractId;
		this.paymentType = paymentType;
		this.paymentDate = paymentDate;
		this.duePeriod = duePeriod;
		this.paymentAmount = paymentAmount;
		this.fineRate = fineRate;
		this.fineAmount = fineAmount;
		this.paid = paid;
	}

	@Id

	@Column(name = "PaymentID", unique = true, nullable = false)
	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "staffID", nullable = false)
	public Staffs getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Staffs staffs) {
		this.staffs = staffs;
	}

	@Column(name = "contractID", nullable = false)
	public int getContractId() {
		return this.contractId;
	}

	public void setContractId(int contractId) {
		this.contractId = contractId;
	}

	@Column(name = "PaymentType", nullable = false)
	public int getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(int paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "PaymentDate", nullable = false, length = 10)
	public String getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(String paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "duePeriod", nullable = false)
	public int getDuePeriod() {
		return this.duePeriod;
	}

	public void setDuePeriod(int duePeriod) {
		this.duePeriod = duePeriod;
	}

	@Column(name = "PaymentAmount", nullable = false, scale = 4)
	public BigDecimal getPaymentAmount() {
		return this.paymentAmount;
	}

	public void setPaymentAmount(BigDecimal paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	@Column(name = "FineRate", nullable = false, precision = 18, scale = 0)
	public long getFineRate() {
		return this.fineRate;
	}

	public void setFineRate(long fineRate) {
		this.fineRate = fineRate;
	}

	@Column(name = "FineAmount", nullable = false, scale = 4)
	public BigDecimal getFineAmount() {
		return this.fineAmount;
	}

	public void setFineAmount(BigDecimal fineAmount) {
		this.fineAmount = fineAmount;
	}

	@Column(name = "paid", nullable = false)
	public boolean isPaid() {
		return this.paid;
	}

	public void setPaid(boolean paid) {
		this.paid = paid;
	}

}
