package entities;
// Generated Aug 7, 2016 11:38:34 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Staffs generated by hbm2java
 */
@Entity
@Table(name = "Staffs", catalog = "vzsoft_chicken_team")
public class Staffs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int staffId;
	private Department department;
	private String staffName;
	private boolean isAdmin;
	private int role;
	private Set<Payment> payments = new HashSet<Payment>(0);

	public Staffs() {
	}

	public Staffs(int staffId, Department department, String staffName, boolean isAdmin, int role) {
		this.staffId = staffId;
		this.department = department;
		this.staffName = staffName;
		this.isAdmin = isAdmin;
		this.role = role;
	}

	public Staffs(int staffId, Department department, String staffName, boolean isAdmin, int role,
			Set<Payment> payments) {
		this.staffId = staffId;
		this.department = department;
		this.staffName = staffName;
		this.isAdmin = isAdmin;
		this.role = role;
		this.payments = payments;
	}

	@Id

	@Column(name = "staffId", unique = true, nullable = false)
	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departmentID", nullable = false)
	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	@Column(name = "staffName", nullable = false, length = 100)
	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	@Column(name = "isAdmin", nullable = false)
	public boolean isIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	@Column(name = "role", nullable = false)
	public int getRole() {
		return this.role;
	}

	public void setRole(int role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staffs")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
