package entities;
// Generated Aug 11, 2016 10:25:57 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "Users", catalog = "vzsoft_chicken_team")
public class Users implements java.io.Serializable {

	private String userName;
	private String fullName;
	private short role;

	public Users() {
	}

	public Users(String userName, String fullName, short role) {
		this.userName = userName;
		this.fullName = fullName;
		this.role = role;
	}

	@Id

	@Column(name = "UserName", unique = true, nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "FullName", nullable = false, length = 100)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "Role", nullable = false)
	public short getRole() {
		return this.role;
	}

	public void setRole(short role) {
		this.role = role;
	}

}
