package entities;
// Generated Aug 7, 2016 11:38:34 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VoucherDetailId generated by hbm2java
 */
@Embeddable
public class VoucherDetailId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int voucherId;
	private int numericalOrder;

	public VoucherDetailId() {
	}

	public VoucherDetailId(int voucherId, int numericalOrder) {
		this.voucherId = voucherId;
		this.numericalOrder = numericalOrder;
	}

	@Column(name = "voucherId", nullable = false)
	public int getVoucherId() {
		return this.voucherId;
	}

	public void setVoucherId(int voucherId) {
		this.voucherId = voucherId;
	}

	@Column(name = "numericalOrder", nullable = false)
	public int getNumericalOrder() {
		return this.numericalOrder;
	}

	public void setNumericalOrder(int numericalOrder) {
		this.numericalOrder = numericalOrder;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VoucherDetailId))
			return false;
		VoucherDetailId castOther = (VoucherDetailId) other;

		return (this.getVoucherId() == castOther.getVoucherId())
				&& (this.getNumericalOrder() == castOther.getNumericalOrder());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVoucherId();
		result = 37 * result + this.getNumericalOrder();
		return result;
	}

}
