package entities;
// Generated Aug 7, 2016 11:38:34 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VoucherDetail generated by hbm2java
 */
@Entity
@Table(name = "VoucherDetail", catalog = "vzsoft_chicken_team")
public class VoucherDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VoucherDetailId id;
	private VoucherHeader voucherHeader;
	private Date startPeriodDate;
	private BigDecimal amountBeforeFines;
	private BigDecimal amountAfterFines;

	public VoucherDetail() {
	}

	public VoucherDetail(VoucherDetailId id, VoucherHeader voucherHeader, Date startPeriodDate,
			BigDecimal amountBeforeFines, BigDecimal amountAfterFines) {
		this.id = id;
		this.voucherHeader = voucherHeader;
		this.startPeriodDate = startPeriodDate;
		this.amountBeforeFines = amountBeforeFines;
		this.amountAfterFines = amountAfterFines;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "voucherId", column = @Column(name = "voucherId", nullable = false)),
			@AttributeOverride(name = "numericalOrder", column = @Column(name = "numericalOrder", nullable = false)) })
	public VoucherDetailId getId() {
		return this.id;
	}

	public void setId(VoucherDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "voucherId", nullable = false, insertable = false, updatable = false)
	public VoucherHeader getVoucherHeader() {
		return this.voucherHeader;
	}

	public void setVoucherHeader(VoucherHeader voucherHeader) {
		this.voucherHeader = voucherHeader;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startPeriodDate", nullable = false, length = 23)
	public Date getStartPeriodDate() {
		return this.startPeriodDate;
	}

	public void setStartPeriodDate(Date startPeriodDate) {
		this.startPeriodDate = startPeriodDate;
	}

	@Column(name = "amountBeforeFines", nullable = false, scale = 4)
	public BigDecimal getAmountBeforeFines() {
		return this.amountBeforeFines;
	}

	public void setAmountBeforeFines(BigDecimal amountBeforeFines) {
		this.amountBeforeFines = amountBeforeFines;
	}

	@Column(name = "amountAfterFines", nullable = false, scale = 4)
	public BigDecimal getAmountAfterFines() {
		return this.amountAfterFines;
	}

	public void setAmountAfterFines(BigDecimal amountAfterFines) {
		this.amountAfterFines = amountAfterFines;
	}

}
