package entities;
// Generated Aug 7, 2016 11:38:34 PM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VoucherHeader generated by hbm2java
 */
@Entity
@Table(name = "VoucherHeader", catalog = "vzsoft_chicken_team")
public class VoucherHeader implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int voucherId;
	private int contractId;
	private Date paymentDate;
	private BigDecimal totalAmountBeforeFines;
	private BigDecimal totalAmountAfterFines;
	private Set<VoucherDetail> voucherDetails = new HashSet<VoucherDetail>(0);

	public VoucherHeader() {
	}

	public VoucherHeader(int voucherId, int contractId, Date paymentDate, BigDecimal totalAmountBeforeFines,
			BigDecimal totalAmountAfterFines) {
		this.voucherId = voucherId;
		this.contractId = contractId;
		this.paymentDate = paymentDate;
		this.totalAmountBeforeFines = totalAmountBeforeFines;
		this.totalAmountAfterFines = totalAmountAfterFines;
	}

	public VoucherHeader(int voucherId, int contractId, Date paymentDate, BigDecimal totalAmountBeforeFines,
			BigDecimal totalAmountAfterFines, Set<VoucherDetail> voucherDetails) {
		this.voucherId = voucherId;
		this.contractId = contractId;
		this.paymentDate = paymentDate;
		this.totalAmountBeforeFines = totalAmountBeforeFines;
		this.totalAmountAfterFines = totalAmountAfterFines;
		this.voucherDetails = voucherDetails;
	}

	@Id

	@Column(name = "voucherId", unique = true, nullable = false)
	public int getVoucherId() {
		return this.voucherId;
	}

	public void setVoucherId(int voucherId) {
		this.voucherId = voucherId;
	}

	@Column(name = "contractId", nullable = false)
	public int getContractId() {
		return this.contractId;
	}

	public void setContractId(int contractId) {
		this.contractId = contractId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "paymentDate", nullable = false, length = 23)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "totalAmountBeforeFines", nullable = false, scale = 4)
	public BigDecimal getTotalAmountBeforeFines() {
		return this.totalAmountBeforeFines;
	}

	public void setTotalAmountBeforeFines(BigDecimal totalAmountBeforeFines) {
		this.totalAmountBeforeFines = totalAmountBeforeFines;
	}

	@Column(name = "totalAmountAfterFines", nullable = false, scale = 4)
	public BigDecimal getTotalAmountAfterFines() {
		return this.totalAmountAfterFines;
	}

	public void setTotalAmountAfterFines(BigDecimal totalAmountAfterFines) {
		this.totalAmountAfterFines = totalAmountAfterFines;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "voucherHeader")
	public Set<VoucherDetail> getVoucherDetails() {
		return this.voucherDetails;
	}

	public void setVoucherDetails(Set<VoucherDetail> voucherDetails) {
		this.voucherDetails = voucherDetails;
	}

}
